FROM ubuntu:18.04
# Install Apache

RUN apt update
RUN apt install apache2 apache2-utils nano git -y
RUN apt update


## below lines to be turned on if crons capability is needed in docker container, customcron file to be updated ad per desired schedule.
#RUN apt install apache2 apache2-utils nano git cron -y
#COPY customcron /etc/cron.d/hello-cron
#RUN chmod 0644 /etc/cron.d/hello-cron
#RUN touch /var/log/cron.log

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN echo "ServerSignature Off" >>  /etc/apache2/apache2.conf
RUN echo "ServerTokens Prod" >>   /etc/apache2/apache2.conf


#set timezone of the containers as per need.
ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install EPEL Repo
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:ondrej/php  -y

#Install PHP & EXTENTIONS
RUN apt update -y
RUN apt install php8.2 -y
RUN apt-get install libapache2-mod-php8.2 php8.2-common php8.2-mbstring  php8.2-soap php8.2-gd php8.2-xml php8.2-intl php8.2-mysql php8.2-cli php8.2-mcrypt php8.2-zip php8.2-curl  php8.2-bcmath -y
#php7.4-xmlrpc php7.4-gmp

RUN apt update
RUN apt install curl
RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
RUN sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN apt update
#RUN apt clean

# Update Apache Configuration
#RUN sed -E -i -e '/<Directory "\/var\/www\/html">/,/<\/Directory>/s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

#RUN sed -E -i -e '/<Directory "\/var\/www\/">/,/<\/Directory>/s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

RUN sed -E -i -e '/Options Indexes FollowSymLinks/,/Require all granted/s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

RUN sed -E -i -e 's/DirectoryIndex (.*)$/DirectoryIndex index.php \1/g' /etc/apache2/apache2.conf


RUN a2enmod rewrite
RUN a2enmod headers

#RUN cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/ && \
#    cp /etc/apache2/mods-available/headers.load /etc/apache2/mods-enabled/

#Configure Php.ini
RUN sed -E -i -e 's/memory_limit = 128M/memory_limit = -1/' /etc/php/8.2/cli/php.ini \
 && sed -E -i -e 's/post_max_size = 8M/post_max_size = 512M/' /etc/php/8.2/cli/php.ini \
 && sed -E -i -e 's/upload_max_filesize = 2M/upload_max_filesize = 64M/' /etc/php/8.2/cli/php.ini \
 && sed -E -i -e 's/;max_input_vars = 1000/max_input_vars = 1000000/' /etc/php/8.2/cli/php.ini \
 && sed -E -i -e 's/expose_php = On/expose_php = Off/' /etc/php/8.2/cli/php.ini

#copy pre/post scripts
COPY run.sh /scripts/run.sh
COPY postrun.sh /scripts/postrun.sh
COPY headless1 /var/www/html/headless


EXPOSE 80
USER root

#RUN start script
ENTRYPOINT ["sh", "/scripts/run.sh" ]
#CMD apache2ctl -D FOREGROUND
#CMD cron && tail -f /var/log/cron.log


