   <?php
    $viewModel = $block->getViewModel();
?>
<h3>Payment Information</h3>
<table>
    <tr>
       
        <td>
            <?php $unique_merchant_txn_id= $viewModel->getUniqueMerchantTxnId(); ?>
         

		<?php if($unique_merchant_txn_id):?>
			<h3>Merchant Transaction Id : <?php echo $unique_merchant_txn_id; ?> </h3>	
			<?php $transaction_response = $viewModel->getTransactionInformation($unique_merchant_txn_id); ?>
			<?php if($transaction_response):?>
				 <?php foreach($transaction_response as $trkey=>$trvalue):?>
					<?php echo $trkey; ?> = <?php echo $trvalue; ?><br/>
				 <?php endforeach; ?>
			<?php else :?>
			<label>No Information available.</label>
				
			<?php endif; ?>
		<?php endif; ?>
           

    </td>
    </tr>

</table>